### ISSUE TITLE
crashes on encountering utf-8

### ISSUE THREAD

**Issue by matkoniecz** [brandon-rhodes/uncommitted#12]
Due to #11 I modified file to include `main()` line at the end.

To reproduce: create git repo with file "ó.txt".

`python2 command.py ~/path_to_test_repo` (without #11 `uncommitted ~/path_to_test_repo` should work).

```
Traceback (most recent call last):
  File "command.py", line 143, in <module>
    main()
  File "command.py", line 141, in main
    scan(repos, options.verbose)
  File "command.py", line 99, in scan
    lines = get_status(directory, ignore_set)
  File "command.py", line 65, in status_git
    lines = run(('git', 'status', '-s', '-b'), cwd=path)
  File "command.py", line 27, in run
    return output.decode().splitlines()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 93: ordinal not in range(128)
```

**Comment by brandon-rhodes** [comment]
What is your system encoding? Run the command `locale` and let's look at its output to see what your system thinks.

**Comment by matkoniecz** [comment]
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=
```

**Comment by AurelienLourot** [comment]
@brandon-rhodes I'm actually working on a fix right now for a similar issue I got on my fork: https://github.com/AurelienLourot/uncommitted/issues/10

The fix is extremely simple and I have it covered by a unit test already. I'm still cleaning up my patches. I'll create a pull request here very soon.

**Comment by AurelienLourot** [comment]
Here you go :)

**Comment by brandon-rhodes** [comment]
Thanks! I think this issue is now resolved thanks to 5cf7169.

**Comment by matkoniecz** [comment]
Note that it means that it will behave poorly in cases where non-ASCII is OK (in extreme case - for example russian/chinese/japanese/etc text will be entirely converted to question marks).

**Comment by AurelienLourot** [comment]
If characters are UTF-8 and the system properly exposes UTF-8 as its default encoding, then everything will be fine (no question marks). Same with any other encoding. The characters just have to match the encoding exposed by the system.

On your system however, it looks different and Python thinks that your default encoding is ASCII:

> UnicodeDecodeError: 'ascii' ...

Which is strange as it contradicts you `locale`. There is something fishy on your system I think. The best we can do here, I think, is not to crash and simply convert chars into `?`.
