### ISSUE TITLE
Add git submodule support (recursive path loop)

### ISSUE THREAD

**Issue by NathanUrwin** [brandon-rhodes/uncommitted#33]
```
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/3.7.1/bin/uncommitted", line 11, in <module>
    sys.exit(main())
  File "/usr/local/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/uncommitted/command.py", line 258, in main
    scan(repos, options)
  File "/usr/local/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/uncommitted/command.py", line 182, in scan
    lines, subrepos = get_status(directory, ignore_set, options)
  File "/usr/local/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/uncommitted/command.py", line 109, in status_git
    lines = [l for l in run(('git', 'status', '-s', '-b'), cwd=path)
  File "/usr/local/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/uncommitted/command.py", line 32, in run
    return check_output(command, **kw).splitlines()
  File "/usr/local/opt/pyenv/versions/3.7.1/lib/python3.7/subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "/usr/local/opt/pyenv/versions/3.7.1/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/opt/pyenv/versions/3.7.1/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/usr/local/opt/pyenv/versions/3.7.1/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 63] File name too long: b'/Users/nathan.urwin/Projects/louis/sdmPythonWrapper/src/pysdm/lib/wharfConfig/./././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././'
```

Fantastic project, please let me know if there's any more information I can provide. Thanks!

**Comment by NathanUrwin** [comment]
Just want to add that this is low priority since `uncommitted -nus * -I louis/sdmPythonWrapper/src/pysdm/lib` is working OK.

**Comment by brandon-rhodes** [comment]
Thanks for the report! Is there a URL that I can clone that repo from? Or another repo you can reproduce the problem with that's public and I could use?

**Comment by NathanUrwin** [comment]
Hey @brandon-rhodes 👋 Thanks for the reply!

Sadly no, this is a propriety company repo... seems to be happening with the same repo though when it's not a submodule. The repo only supports python2, whereas I'm running uncommitted from python3... maybe that's the issue? Thanks in advance for your time!

**Comment by brandon-rhodes** [comment]
Happily, "uncommitted" makes no attempt to run any code in the repositories it's looking at, so there can't be a problem with the version of Python code stored there.

My temptation in your case would be to edit the source code of "uncommitted" and try adding a `print` statement right above the line from `status_git()` you see in the traceback, right above the line that includes the phrase `cwd=path` — you'll want to print `path` and see if that's the source of the huge path with all the dots in it. If so, we'll want to figure out how "uncommitted" is building that path and why.

Unless you can create a sample repo with the same error, I won't be able to dive into this myself — but with a couple more print statements you can probably figure out what's going on. Good luck!

**Comment by NathanUrwin** [comment]
In regards to me cloning the source and adding print statements, have you come across python's [standard logging library](https://docs.python.org/3/library/logging.html)? 

Once I have some free time, I'll definitely dive into this issue for you though! Maybe I'll add a feature branch that adds logging support if you would be interesting in merging something like that.

Thanks in advance for your time and this awesome project! 😄

**Comment by brandon-rhodes** [comment]
I'm going to temporarily close this issue pending further information about how those paths are getting generated. But lacking a test case that I myself can use to reproduce the problem, I'm going to close this as un-actionable for now. If you do come up with more information, please don't hesitate to re-open this issue and post! Thanks.
